# ~/.config/nix/nix.conf
# https://nix.dev/manual/nix/2.18/command-ref/conf-file.html

auto-optimise-store = true

keep-outputs = true       # Nice for developers
keep-derivations = true   # Idem

# https://nixos.wiki/wiki/Ca-derivations
# https://nix.dev/manual/nix/2.28/development/experimental-features#xp-feature-ca-derivations
# experimental-features = ca-derivations

# https://discourse.nixos.org/t/ca-derivations-is-disabled-regardless-of-config-on-mac-os-solved/33550/2
# experimental-features needs to go in /etc/nix/nix.conf
# then force config reload with
# sudo launchctl stop org.nixos.nix-daemon
